@extends('admin.layouts.app')

@section('title', __('Payment :reference', ['reference' => $payment->reference]))

@php
    $approvalErrors = $errors->getBag('paymentApproval');
    $rejectionErrors = $errors->getBag('paymentRejection');
    $snapshot = is_array($payment->plan_snapshot) ? $payment->plan_snapshot : [];
    $snapshotFeatures = collect($snapshot['features'] ?? [])->filter(fn ($feature) => is_string($feature) && trim($feature) !== '');
    $snapshotLimits = collect($snapshot['limits'] ?? [])->filter(fn ($value, $key) => array_key_exists($key, \App\Models\Plan::LIMITS));
    $statusClass = match ($payment->status) { \App\Enums\PaymentStatus::PAID => 'nd-status-success', \App\Enums\PaymentStatus::PENDING => 'nd-status-warning', \App\Enums\PaymentStatus::REJECTED, \App\Enums\PaymentStatus::CANCELED, \App\Enums\PaymentStatus::EXPIRED => 'nd-status-danger', default => 'nd-status-muted' };
    $difference = abs($payment->submitted_amount_minor - $payment->expected_amount_minor);
@endphp

@section('content')
    <div class="nd-payment-detail-header"><div><h1>{{ __('Payment :reference', ['reference' => $payment->reference]) }}</h1><span class="nd-status-badge {{ $statusClass }}">{{ $payment->status->label() }}</span></div><a class="btn nd-btn-secondary" href="{{ route('admin.payments.index') }}"><i class="iconoir-arrow-left" aria-hidden="true"></i>{{ __('Back') }}</a></div>
    @if ($payment->hasAmountMismatch())<div class="nd-payment-warning" role="alert"><i class="iconoir-warning-triangle" aria-hidden="true"></i><div><strong>{{ __('Amount mismatch') }}</strong><span>{{ __('The submitted amount differs from the expected amount by :amount. Approval requires an explicit acknowledgement.', ['amount' => $payment->currency.' '.\App\Services\DecimalMoney::fromMinor($difference)]) }}</span></div></div>@endif

    <div class="row g-4 nd-payment-detail-grid"><div class="col-12 col-xl-8">
        <section class="card nd-card nd-payment-detail-card" aria-labelledby="payment-details-title"><div class="card-body"><h2 id="payment-details-title">{{ __('Payment Details') }}</h2><dl class="nd-payment-data-grid">
            <div><dt>{{ __('Expected amount') }}</dt><dd>{{ $payment->formattedExpectedAmount() }}</dd></div><div><dt>{{ __('Submitted amount') }}</dt><dd class="{{ $payment->hasAmountMismatch() ? 'text-danger' : '' }}">{{ $payment->formattedSubmittedAmount() }}</dd></div><div><dt>{{ __('Currency') }}</dt><dd>{{ $payment->currency }}</dd></div><div><dt>{{ __('Method') }}</dt><dd>{{ $payment->payment_method->label() }}</dd></div><div><dt>{{ __('Reference') }}</dt><dd>{{ $payment->reference }}</dd></div><div><dt>{{ __('Invoice') }}</dt><dd>{{ $payment->invoice?->number ?? __('Not available') }}</dd></div><div><dt>{{ __('Subscriber') }}</dt><dd>{{ $payment->user?->name ?? __('Former subscriber') }}</dd></div><div><dt>{{ __('Subscriber email') }}</dt><dd>{{ $payment->user?->email ?? __('Not available') }}</dd></div><div><dt>{{ __('Workspace') }}</dt><dd>{{ __('Not available in the current schema') }}</dd></div><div><dt>{{ __('Selected plan') }}</dt><dd>{{ $payment->plan_name_snapshot }}</dd></div><div><dt>{{ __('Plan interval') }}</dt><dd>{{ $payment->plan_interval_snapshot->label() }}</dd></div><div><dt>{{ __('Submitted') }}</dt><dd>{{ $payment->submitted_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('N/A') }}</dd></div><div><dt>{{ __('Transfer date') }}</dt><dd>{{ $payment->transferred_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('N/A') }}</dd></div><div><dt>{{ __('Paid date') }}</dt><dd>{{ $payment->paid_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('Not paid') }}</dd></div><div><dt>{{ __('Reviewed') }}</dt><dd>{{ $payment->reviewed_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('Not reviewed') }}</dd></div><div><dt>{{ __('Reviewer') }}</dt><dd>{{ $payment->reviewer?->name ?? __('Not reviewed') }}</dd></div><div class="nd-payment-data-wide"><dt>{{ __('Description') }}</dt><dd>{{ $payment->invoice?->description ?? $payment->plan_name_snapshot.' '.__('subscription') }}</dd></div>
        </dl></div></section>

        <div class="row g-4 mt-0"><div class="col-12 col-lg-6"><section class="card nd-card nd-payment-detail-card h-100" aria-labelledby="plan-snapshot-title"><div class="card-body"><h2 id="plan-snapshot-title">{{ __('Plan Snapshot') }}</h2><dl class="nd-payment-data-list"><div><dt>{{ __('Plan') }}</dt><dd>{{ $snapshot['name'] ?? $payment->plan_name_snapshot }}</dd></div><div><dt>{{ __('Interval') }}</dt><dd>{{ $payment->plan_interval_snapshot->label() }}</dd></div><div><dt>{{ __('Price') }}</dt><dd>{{ $payment->formattedExpectedAmount() }}</dd></div></dl><h3>{{ __('Features at purchase') }}</h3>@if ($snapshotFeatures->isEmpty())<p class="nd-payment-empty-copy">{{ __('No feature snapshot was recorded.') }}</p>@else<ul class="nd-payment-feature-list">@foreach ($snapshotFeatures as $feature)<li><i class="iconoir-check-circle" aria-hidden="true"></i>{{ $feature }}</li>@endforeach</ul>@endif @if ($snapshotLimits->isNotEmpty())<div class="nd-payment-limit-list">@foreach ($snapshotLimits as $key => $limit)<span>{{ __(\App\Models\Plan::LIMITS[$key]) }}: <strong>{{ (int) $limit === 0 ? __('Unlimited') : number_format((int) $limit) }}</strong></span>@endforeach</div>@endif</div></section></div>
        <div class="col-12 col-lg-6"><section class="card nd-card nd-payment-detail-card h-100" aria-labelledby="bank-details-title"><div class="card-body"><h2 id="bank-details-title">{{ __('Bank Transfer Details') }}</h2><dl class="nd-payment-data-list"><div><dt>{{ __('Payer name') }}</dt><dd>{{ $payment->payer_name }}</dd></div><div><dt>{{ __('Payer bank') }}</dt><dd>{{ $payment->payer_bank_name }}</dd></div><div><dt>{{ __('Transaction reference') }}</dt><dd>{{ $payment->transaction_reference }}</dd></div><div><dt>{{ __('Transfer date') }}</dt><dd>{{ $payment->transferred_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('N/A') }}</dd></div><div><dt>{{ __('Subscriber notes') }}</dt><dd>{{ $payment->notes ?: __('No notes provided') }}</dd></div></dl></div></section></div></div>

        <section class="card nd-card nd-payment-detail-card mt-4" aria-labelledby="proof-title"><div class="card-body"><h2 id="proof-title">{{ __('Payment Proof') }}</h2>@if ($payment->proof)<div class="nd-payment-proof"><span class="nd-payment-proof-icon"><i class="iconoir-attachment" aria-hidden="true"></i></span><div><strong>{{ $payment->proof->original_name }}</strong><span>{{ $payment->proof->mime_type }} · {{ Number::fileSize($payment->proof->size) }} · {{ $payment->proof->created_at?->diffForHumans() }}</span></div><a class="btn nd-btn-secondary" href="{{ route('admin.payments.proof.download', $payment) }}"><i class="iconoir-download" aria-hidden="true"></i>{{ __('View or download') }}</a></div>@else<div class="nd-payment-empty-copy" role="status">{{ __('No payment proof is attached. This payment cannot be approved.') }}</div>@endif</div></section>
    </div>

    <div class="col-12 col-xl-4"><aside class="card nd-card nd-payment-review-card" aria-labelledby="review-payment-title"><div class="card-body"><h2 id="review-payment-title">{{ __('Review Payment') }}</h2>@if ($payment->status === \App\Enums\PaymentStatus::PENDING)
        <div class="nd-review-summary"><div><span>{{ __('Expected') }}</span><strong>{{ $payment->formattedExpectedAmount() }}</strong></div><div><span>{{ __('Submitted') }}</span><strong>{{ $payment->formattedSubmittedAmount() }}</strong></div><div><span>{{ __('Proof') }}</span><strong>{{ $payment->proof ? __('Available') : __('Missing') }}</strong></div></div><button class="btn nd-btn-success w-100" type="button" data-bs-toggle="modal" data-bs-target="#approve-payment-modal" @disabled(! $payment->proof)><i class="iconoir-check-circle" aria-hidden="true"></i>{{ __('Approve & Activate Plan') }}</button><button class="btn nd-btn-danger-outline w-100 mt-2" type="button" data-bs-toggle="modal" data-bs-target="#reject-payment-modal"><i class="iconoir-xmark-circle" aria-hidden="true"></i>{{ __('Reject Payment') }}</button>
    @else<div class="nd-reviewed-summary"><span class="nd-status-badge {{ $statusClass }}">{{ $payment->status->label() }}</span><dl><div><dt>{{ __('Reviewed by') }}</dt><dd>{{ $payment->reviewer?->name ?? __('Not available') }}</dd></div><div><dt>{{ __('Reviewed at') }}</dt><dd>{{ $payment->reviewed_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('Not available') }}</dd></div>@if ($payment->reviewNote())<div><dt>{{ __('Review note') }}</dt><dd>{{ $payment->reviewNote() }}</dd></div>@endif @if ($payment->rejection_reason)<div><dt>{{ __('Subscriber-visible reason') }}</dt><dd>{{ $payment->rejection_reason }}</dd></div>@endif @if ($payment->subscription)<div><dt>{{ __('Access until') }}</dt><dd>{{ $payment->subscription->current_period_ends_at?->timezone(config('app.timezone'))->format('d M, Y \a\t h:i A') ?? __('N/A') }}</dd></div>@endif</dl></div>@endif
    </div></aside></div></div>

    @if ($payment->status === \App\Enums\PaymentStatus::PENDING)
        <div class="modal fade" id="approve-payment-modal" tabindex="-1" aria-labelledby="approve-payment-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content nd-confirm-modal"><div class="modal-header"><h2 class="modal-title fs-5" id="approve-payment-title">{{ __('Approve payment') }}</h2><button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal" aria-label="{{ __('Close') }}"></button></div><form method="POST" action="{{ route('admin.payments.approve', $payment) }}" data-payment-submit-once>@csrf<div class="modal-body"><p>{{ __('This marks the payment and invoice paid, activates :plan, and preserves the previous subscription in history.', ['plan' => $payment->plan_name_snapshot]) }}</p><div class="mb-3"><label class="form-label" for="approval-review-note">{{ __('Private review note') }}</label><textarea class="form-control {{ $approvalErrors->has('review_note') ? 'is-invalid' : '' }}" id="approval-review-note" name="review_note" rows="3" maxlength="2000">{{ old('review_note') }}</textarea>@if ($approvalErrors->has('review_note'))<div class="invalid-feedback">{{ $approvalErrors->first('review_note') }}</div>@endif</div>@if ($payment->hasAmountMismatch())<div class="form-check nd-mismatch-check"><input class="form-check-input" id="amount-mismatch-acknowledged" name="amount_mismatch_acknowledged" type="checkbox" value="1" required><label class="form-check-label" for="amount-mismatch-acknowledged">{{ __('I reviewed and explicitly accept the amount mismatch.') }}</label></div>@endif<input name="confirmation" type="hidden" value="1"></div><div class="modal-footer"><button class="btn nd-btn-secondary" type="button" data-bs-dismiss="modal">{{ __('Cancel') }}</button><button class="btn nd-btn-success" type="submit" data-payment-submit-button data-loading-label="{{ __('Approving...') }}">{{ __('Approve & Activate Plan') }}</button></div></form></div></div></div>
        <div class="modal fade" id="reject-payment-modal" tabindex="-1" aria-labelledby="reject-payment-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content nd-confirm-modal"><div class="modal-header"><h2 class="modal-title fs-5" id="reject-payment-title">{{ __('Reject payment') }}</h2><button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal" aria-label="{{ __('Close') }}"></button></div><form method="POST" action="{{ route('admin.payments.reject', $payment) }}" data-payment-submit-once>@csrf<div class="modal-body"><p>{{ __('The selected plan will not be activated. The reason below will be visible to the subscriber.') }}</p><div class="mb-3"><label class="form-label" for="rejection-reason">{{ __('Rejection reason') }} <span class="text-danger">*</span></label><textarea class="form-control {{ $rejectionErrors->has('rejection_reason') ? 'is-invalid' : '' }}" id="rejection-reason" name="rejection_reason" rows="4" minlength="3" maxlength="2000" required>{{ old('rejection_reason') }}</textarea>@if ($rejectionErrors->has('rejection_reason'))<div class="invalid-feedback">{{ $rejectionErrors->first('rejection_reason') }}</div>@endif</div><div><label class="form-label" for="rejection-review-note">{{ __('Private review note') }}</label><textarea class="form-control {{ $rejectionErrors->has('review_note') ? 'is-invalid' : '' }}" id="rejection-review-note" name="review_note" rows="3" maxlength="2000"></textarea></div><input name="confirmation" type="hidden" value="1"></div><div class="modal-footer"><button class="btn nd-btn-secondary" type="button" data-bs-dismiss="modal">{{ __('Cancel') }}</button><button class="btn nd-btn-danger" type="submit" data-payment-submit-button data-loading-label="{{ __('Rejecting...') }}">{{ __('Reject Payment') }}</button></div></form></div></div></div>
    @endif
@endsection

@push('scripts')<script src="{{ asset('js/admin-payments.js') }}"></script>@endpush
